name: CI - main branch

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
  schedule:
    # Nightly tests run on main by default:
    #   Scheduled workflows run on the latest commit on the default or base branch.
    #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - 3.12

    env:
      CI_OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        name: Install dependencies
        with:
          python-version: ${{ matrix.python }}
          environment-file: environment.yml
          auto-activate-base: false
          miniforge-variant: Miniforge3
          use-mamba: true

      - name: Describe environment
        run: |
          pwd
          ls
          conda list

      - name: Run example notebooks
        shell: bash -l {0}
        # --nbval-lax: Only check output when cell is marked
        # https://nbval.readthedocs.io/en/latest/#Using-tags-instead-of-comments
        run: pytest -v --nbval-lax notebooks/cookbook
